#pragma once

#define PLAYER_ENEMY_RADIUS 4
#define ENEMY_HEURISTIC_ADDITIVE 200
#define NUMBER_OF_ENEMIES 2
#define CHASE_PLAYER_TIME 2
#define EVADE_PLAYER_TIME 1
#define PLAYER_RANDOM_EVADE_LIMIT 4